package usecase

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/mmycin/GoForge/internal/infra"
	"github.com/mmycin/GoForge/internal/scaffold"
)

// GenServiceUseCase generates the full service layer for a given name.
type GenServiceUseCase struct {
	gen *scaffold.Generator
	fs  infra.FileSystem
}

// NewGenServiceUseCase constructs a GenServiceUseCase.
func NewGenServiceUseCase(gen *scaffold.Generator, fs infra.FileSystem) *GenServiceUseCase {
	return &GenServiceUseCase{gen: gen, fs: fs}
}

// Run generates all service files and updates kernel.go.
func (uc *GenServiceUseCase) Run(name, modulePath string, progress Progress) error {
	targetDir := filepath.Join("internal/services", name)

	if uc.gen.Exists(targetDir) {
		return fmt.Errorf("service %q already exists at %s", name, targetDir)
	}

	typeName := scaffold.ToCamelCase(name)
	data := scaffold.ServiceData{
		PackageName: name,
		TypeName:    typeName,
		ModulePath:  modulePath,
	}

	serviceFiles := []struct {
		tmpl string
		dest string
	}{
		{"service/service.go.tmpl", filepath.Join(targetDir, "service.go")},
		{"service/handler.go.tmpl", filepath.Join(targetDir, "handler.go")},
		{"service/model.go.tmpl", filepath.Join(targetDir, "model.go")},
		{"service/routes.go.tmpl", filepath.Join(targetDir, "routes.go")},
		{"service/docs.go.tmpl", filepath.Join(targetDir, "docs.go")},
		{"service/grpc.go.tmpl", filepath.Join(targetDir, "grpc.go")},
	}

	var generated []GeneratedFile
	for _, f := range serviceFiles {
		send(progress, StepStarted{Label: "Writing " + filepath.Base(f.dest)})
		if err := uc.gen.Generate(f.tmpl, data, f.dest); err != nil {
			send(progress, StepFailed{Label: filepath.Base(f.dest), Err: err})
			return err
		}
		generated = append(generated, GeneratedFile{Path: f.dest})
		send(progress, StepDone{Label: "Writing " + filepath.Base(f.dest)})
	}

	// Proto file
	protoDir := filepath.Join("internal/proto", name)
	protoDest := filepath.Join(protoDir, name+".proto")
	protoData := scaffold.ProtoData{PackageName: name, TypeName: typeName, ModulePath: modulePath}
	send(progress, StepStarted{Label: "Writing proto file"})
	if err := uc.gen.Generate("proto/service.proto.tmpl", protoData, protoDest); err != nil {
		send(progress, StepFailed{Label: "Writing proto file", Err: err})
		// non-fatal
	} else {
		generated = append(generated, GeneratedFile{Path: protoDest})
		send(progress, StepDone{Label: "Writing proto file"})
	}

	// Regenerate kernel.go
	send(progress, StepStarted{Label: "Updating kernel.go"})
	if err := uc.regenerateKernel(modulePath); err != nil {
		send(progress, LogLine{Level: "warn", Text: fmt.Sprintf("kernel.go update: %v", err)})
	} else {
		generated = append(generated, GeneratedFile{Path: "internal/services/kernel.go", Updated: true})
		send(progress, StepDone{Label: "Updating kernel.go"})
	}

	send(progress, UseCaseDone{Files: generated})
	return nil
}

// ─── kernel.go regeneration ──────────────────────────────────────────────────

func (uc *GenServiceUseCase) regenerateKernel(modulePath string) error {
	return regenerateKernel(uc.fs, modulePath)
}

// svcInfo represents a discovered service and its exported model struct names.
type svcInfo struct {
	Name   string
	Models []string
}

// regenerateKernel regenerates ONLY kernel_models.go (the Model() function).
// InitializeServices is owned by the developer after initial scaffold and is
// never overwritten — that prevents breakage when constructors change.
func regenerateKernel(fsys infra.FileSystem, modulePath string) error {
	entries, err := fsys.ReadDir("internal/services")
	if err != nil {
		return err
	}

	var services []svcInfo
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		// skip kernel files
		if e.Name() == "kernel.go" || e.Name() == "kernel_models.go" {
			continue
		}
		modelPath := filepath.Join("internal/services", e.Name(), "model.go")
		if _, statErr := fsys.Stat(modelPath); statErr != nil {
			continue
		}
		content, err := fsys.ReadFile(modelPath)
		if err != nil {
			continue
		}
		models, err := parseModelStructs(content)
		if err != nil || len(models) == 0 {
			models = []string{scaffold.ToCamelCase(e.Name())}
		}
		services = append(services, svcInfo{Name: e.Name(), Models: models})
	}

	// kernel_models.go: only the Model() function — safe to always regenerate.
	const modelsTmpl = `package services

// Code generated by GoForge. DO NOT EDIT.
// This file lists all GORM models for auto-migration.
// Add new services with: goforge gen:service <name>

import (
{{- range .Services}}
	"{{$.ModulePath}}/internal/services/{{.Name}}"
{{- end}}
)

// Model returns all GORM models that should be auto-migrated.
func Model() []any {
	return []any{
{{- range $svc := .Services}}
	{{- range .Models}}
		&{{$svc.Name}}.{{.}}{},
	{{- end}}
{{- end}}
	}
}
`

	funcMap := template.FuncMap{"title": scaffold.ToCamelCase}
	t, err := template.New("models").Funcs(funcMap).Parse(modelsTmpl)
	if err != nil {
		return err
	}

	var buf strings.Builder
	data := struct {
		ModulePath string
		Services   []svcInfo
	}{ModulePath: modulePath, Services: services}
	if err := t.Execute(&buf, data); err != nil {
		return err
	}

	if err := fsys.WriteFile("internal/services/kernel_models.go", []byte(buf.String()), 0644); err != nil {
		return err
	}

	// kernel.go: only create it if it doesn't exist yet — never overwrite.
	kernelPath := "internal/services/kernel.go"
	if _, statErr := fsys.Stat(kernelPath); statErr == nil {
		// Already exists — remove the old auto-generated Model() function from it
		// if present, to avoid duplicate function declaration with kernel_models.go.
		return removeModelFuncFromKernel(fsys, kernelPath)
	}

	return writeInitialKernel(fsys, modulePath, services)
}

// removeModelFuncFromKernel removes the Model() function body from the legacy
// kernel.go so it doesn't clash with the new kernel_models.go.
func removeModelFuncFromKernel(fsys infra.FileSystem, path string) error {
	content, err := fsys.ReadFile(path)
	if err != nil {
		return nil // not fatal
	}
	src := string(content)

	// Remove the generated Model() func block (from "func Model()" to matching "}")
	// Use a simple marker-based approach — look for the comment we add.
	markers := []string{
		"// Model returns all GORM models that should be auto-migrated.\nfunc Model()",
		"// Model returns all models to be registered with GORM\nfunc Model()",
		"func Model() []any {",
	}

	for _, marker := range markers {
		if idx := strings.Index(src, marker); idx != -1 {
			// Find the end of this function by counting braces from the opening {
			start := idx
			openBrace := strings.Index(src[idx:], "{")
			if openBrace == -1 {
				continue
			}
			pos := idx + openBrace
			depth := 0
			end := pos
			for i := pos; i < len(src); i++ {
				switch src[i] {
				case '{':
					depth++
				case '}':
					depth--
					if depth == 0 {
						end = i + 1
						goto found
					}
				}
			}
		found:
			// Also remove any preceding comment block
			src = src[:start] + src[end:]
			// Remove trailing blank lines
			src = strings.TrimRight(src, "\n") + "\n"
			break
		}
	}

	return fsys.WriteFile(path, []byte(src), 0644)
}

// writeInitialKernel creates kernel.go for the very first time.
// This is the developer's file — only written once, never overwritten.
func writeInitialKernel(fsys infra.FileSystem, modulePath string, services []svcInfo) error {
const initialTmpl = `package services

import (
	"{{.ModulePath}}/boot/server"
	"{{.ModulePath}}/core/database"
{{- range .Services}}
	"{{$.ModulePath}}/internal/services/{{.Name}}"
{{- end}}
)

// ServicesConfig holds all dependencies required to initialise services.
type ServicesConfig struct {
	DB *database.Database
}

// InitializeServices initialises all registered services and returns their routers.
// NOTE: This file is created once by GoForge and is yours to modify.
// Changing service constructors? Update the wiring below manually.
func InitializeServices(cfg ServicesConfig) ([]server.Router, []server.GRPCRegistry) {
	var routers []server.Router
	var grpcRegistries []server.GRPCRegistry
{{- range .Services}}
	{{.Name}}Svc     := {{.Name}}.New{{title .Name}}Service(cfg.DB)
	{{.Name}}Handler := {{.Name}}.New{{title .Name}}Handler({{.Name}}Svc)
	{{.Name}}Routes  := {{.Name}}.New{{title .Name}}Routes({{.Name}}Handler)
	{{.Name}}Docs    := {{.Name}}.New{{title .Name}}Docs()
	routers = append(routers, {{.Name}}Routes, {{.Name}}Docs)
{{- end}}
	return routers, grpcRegistries
}
`
	funcMap := template.FuncMap{"title": scaffold.ToCamelCase}
	t, err := template.New("kernel").Funcs(funcMap).Parse(initialTmpl)
	if err != nil {
		return err
	}

	var buf strings.Builder
	data := struct {
		ModulePath string
		Services   []svcInfo
	}{ModulePath: modulePath, Services: services}
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	return fsys.WriteFile("internal/services/kernel.go", []byte(buf.String()), 0644)
}

func parseModelStructs(content []byte) ([]string, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "", content, 0)
	if err != nil {
		return nil, err
	}
	var models []string
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if _, ok := ts.Type.(*ast.StructType); ok && ast.IsExported(ts.Name.Name) {
				models = append(models, ts.Name.Name)
			}
		}
	}
	return models, nil
}
